services:
  api1:
    build: .
    ports:
      - "4001:3001"
    environment:
      - ID=1
      - PORT=3001
      - GIN_MODE=release

  api2:
    build: .
    ports:
      - "4002:3002"
    environment:
      - ID=2
      - PORT=3002
      - GIN_MODE=release

  reverseproxy:
    build: ./reverseproxy
    ports:
      - "3333:80"
    depends_on:
      - api1
      - api2
