services:
  api1:
    image: dontomato/serviceexp:gs-ping
    restart: always 
    environment:
      - ID=1
      - PORT=3001
      - GIN_MODE=release

  api2:
    image: dontomato/serviceexp:gs-ping
    restart: always 
    environment:
      - ID=2
      - PORT=3002
      - GIN_MODE=release

  reverseproxy:
    image: dontomato/serviceexp:gs-rp
    restart: always 
    ports:
      - "80:80"
    depends_on:
      - api1
      - api2